services:
  - type: web
    name: afterhours-hvac
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: afterhours-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: afterhours-db
    databaseName: afterhours_hvac
    user: afterhours
    plan: starter
